const express = require('express')

const router= express.Router()
const authToken = require('../middleware/authToken.js')
const getCategoryProduct = require('../controller/Product/getCategoryProductOne.js')
const userSignupController = require('../controller/User/userSignup.js')
const userSigninController = require('../controller/User/userSignin.js')
const userDetailsController = require('../controller/User/userDetails.js')
const allUsers = require('../controller/User/allUsers.js')
const updateUser = require('../controller/User/updateUser.js')
const UploadProductController = require('../controller/Product/uploadProduct.js')
const getProductController = require('../controller/Product/getProduct.js')
const updateProductController = require('../controller/Product/updateProduct.js')
const userLogout = require('../controller/User/userLogout.js')
const getCategoryWiseProduct = require('../controller/Product/getCategoryWiseProduct.js')
router.post("/signup",userSignupController)
router.post("/login",userSigninController)
router.get("/user-details",authToken,userDetailsController)
router.get("/logout",userLogout)
router.get("/all-users",authToken,allUsers)
router.post("/update-user",authToken,updateUser)
router.post("/upload-product",authToken,UploadProductController)

router.get("/get-product",getProductController)
router.post("/update-product",authToken,updateProductController)
router.get("/get-categoryProduct",getCategoryProduct)
router.post("/category-product",getCategoryWiseProduct)

module.exports = router